export const queryKeys = {
  staff: ['staff'] as const,
  organizationUnits: ['organizationunits'] as const,
  groups: ['groups'] as const,
  staff2groups: ['staff2groups'] as const,
  questions: ['questions'] as const,
  activeQuestions: ['questions-active'] as const,
  activePeriods: ['evaluation-periods-active'] as const,
  allPeriods: ['evaluation-periods-all'] as const,
  myGroups: (staffId: number | null) => ['myGroups', staffId] as const,
  colleagues: (groupId: number | null, myStaffId: number | null) => ['colleagues', groupId, myStaffId] as const,
  myEvaluations: (groupId: number | null, periodId?: number | null) => ['myEvaluations', groupId, periodId] as const,
  myEvaluationsForDashboard: (staffId: number | null, periodId?: number | null) => ['myEvaluationsForDashboard', staffId, periodId] as const,
  myReceivedEvaluations: (staffId: number | null, periodId?: number | null) => ['myReceivedEvaluations', staffId, periodId] as const,
  receivedEvaluations: (periodId: number | null) => ['receivedEvaluations', periodId] as const,
  givenEvaluations: (periodId: number | null, groupId?: number | null) => ['givenEvaluations', periodId, groupId] as const,
  allEvaluations: (periodId: number | null) => ['allEvaluations', periodId] as const,
  staffReceivedEvaluations: (staffId: number | null, periodId: number | null) => ['staffReceivedEvaluations', staffId, periodId] as const,
  usersRoles: ['users-roles'] as const,
  rolePermissions: ['role-permissions'] as const,
  myProgress: ['my-progress'] as const,
  pendingEvaluations: ['pending-evaluations'] as const,
} as const;
